# https://taskfile.dev

version: "3"

tasks:
  install:
    cmds:
      - uv sync --dev
      - uv run pre-commit install

  run:
    cmds:
      - uv run mcp run "src/mcp_server/server.py" -t sse

  inspector:
    cmds:
      # 2025-03-28 -- Only works on port 3000 for now... (can't change SERVER_PORT)
      - npx @modelcontextprotocol/inspector
